
package dominio;

public enum EventoFachada {

    MESA_NUEVA, MESA_INICIADA, MESA_FINALIZADA,
    MESA_ACTUALIZARJUGADORES,
    MANO_ESPERANDOAPUESTA,
    MANO_APUESTAINICIADA,
    MANO_PIDIENDOCARTAS,
    MANO_TERMINADA,
    JUGADOR_ACCIONPENDIENTE,
    JUGADOR_APUESTAINICIADA,
    JUGADOR_APUESTAPAGADA,
    JUGADOR_NOPAGOAPUESTA

}
