package iuswing;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        itemMenuLogin = new javax.swing.JMenu();
        itemLoginJugador = new javax.swing.JMenuItem();
        itemLoginAdministrador = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenu();
        itemLogoutCerrarSesion = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemMenuLogin.setText("LogIn");

        itemLoginJugador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemLoginJugador.setText("Login Jugador");
        itemLoginJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginJugadorActionPerformed(evt);
            }
        });
        itemMenuLogin.add(itemLoginJugador);

        itemLoginAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemLoginAdministrador.setText("Login Administrador");
        itemLoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginAdministradorActionPerformed(evt);
            }
        });
        itemMenuLogin.add(itemLoginAdministrador);

        jMenuBar3.add(itemMenuLogin);

        menuLogOut.setText("LogOut");

        itemLogoutCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemLogoutCerrarSesion.setText("Cerrar sesión");
        itemLogoutCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutCerrarSesionActionPerformed(evt);
            }
        });
        menuLogOut.add(itemLogoutCerrarSesion);

        jMenuBar3.add(menuLogOut);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginAdministradorActionPerformed
        loginAdministrador();
    }//GEN-LAST:event_itemLoginAdministradorActionPerformed

    private void itemLoginJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginJugadorActionPerformed
        loginJugador();
    }//GEN-LAST:event_itemLoginJugadorActionPerformed

    private void itemLogoutCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerarSesion();
    }//GEN-LAST:event_itemLogoutCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLoginAdministrador;
    private javax.swing.JMenuItem itemLoginJugador;
    private javax.swing.JMenuItem itemLogoutCerrarSesion;
    private javax.swing.JMenu itemMenuLogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menuLogOut;
    // End of variables declaration//GEN-END:variables

    private void cerarSesion() {
        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }


    private void loginAdministrador() {
        Login loginAdministrador = new LoginAdministrador(this, false);
        loginAdministrador.setVisible(true);
    }

    private void loginJugador() {
        Login loginJugador = new LoginJugador(this, false);
        loginJugador.setVisible(true);
    }
}
